Repository kyma-project/application-connector-manager, pull requests merged in 2023-10, with the labels that each got.

#52 fix hosts property for istio resources
  Makefile
  application-connector-dependencies.yaml
  controllers/applicationconnector_controller.go
  controllers/predicate.go
  go.mod
  go.sum
  main.go
  pkg/common/controller-runtime/predicate/deployment.go
  pkg/common/controller-runtime/predicate/gateway.go
  pkg/common/controller-runtime/predicate/virtual_service.go
  pkg/common/types/types.go
  pkg/dependencies/istio/gateway.go
  pkg/dependencies/istio/virtual_service.go
  pkg/reconciler/apply.go
  pkg/reconciler/check_dependencies.go
  pkg/reconciler/fsm.go
  pkg/reconciler/gateway_matecher_test.go
  pkg/reconciler/testdata/update/deps-valid.yaml
  pkg/reconciler/update_objects.go
  pkg/reconciler/update_objects_test.go
  pkg/reconciler/verify.go
  pkg/reconciler/virtual_service_matcher_test.go
Labels: size/XXL, lgtm

#54 Adding security scanners configuration
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#56 Adapt module build to kyma API changes
  Makefile
  module-config-template.yaml
Labels: size/M, lgtm

#57 Fix missing render-manifest recipe in module-build
  Makefile
Labels: size/XS, lgtm

#55 Add busola UI extension
  config/default/kustomization.yaml
  config/ui-extensions/applicationconnectors/details
  config/ui-extensions/applicationconnectors/form
  config/ui-extensions/applicationconnectors/general
  config/ui-extensions/applicationconnectors/kustomization.yaml
  config/ui-extensions/applicationconnectors/list
  config/ui-extensions/kustomization.yaml
Labels: size/L, lgtm

#58 Fix invalid git origin
  Makefile
Labels: size/XS, lgtm

#59 Update project configuration
  .env
  config/crd/bases/operator.kyma-project.io_applicationconnectors.yaml
  config/default/kustomization.yaml
  sec-scanners-config-local.yaml
Labels: size/S, lgtm

#60 Use default TLS configuration in application-connector Istio gateway
  application-connector-dependencies.yaml
Labels: size/XS, lgtm

#61 Add domain name detection
  api/v1alpha1/applicationconnector_types.go
  config/crd/bases/operator.kyma-project.io_applicationconnectors.yaml
  controllers/applicationconnector_controller_test.go
  main.go
  pkg/reconciler/detect_domain.go
  pkg/reconciler/detect_domain_test.go
  pkg/reconciler/initialize.go
  pkg/reconciler/manage_compass_rt_agent.go
  pkg/reconciler/mocks/Client.go
  pkg/reconciler/system_state.go
  pkg/reconciler/update_objects.go
  pkg/reconciler/update_objects_test.go
Labels: size/XL, lgtm

#63 update security scanner config file
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#65 Update to version 0.0.4
  .env
Labels: size/XS, lgtm

#66 Remove auth-proxy
  .env
  application-connector-manager.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
Labels: size/XL, lgtm

#67 Update golang version to 1.21
  Dockerfile
  go.mod
  go.sum
Labels: size/XS, lgtm

#70 Update version 0.0.9
  .env
Labels: size/XS, lgtm

#71 Update sec scanner file image reference
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#72 Update domain for istio gateway
  .env
  pkg/reconciler/update_objects.go
Labels: size/XS, lgtm

#73 fix istio gateway unit tests
  application-connector-dependencies.yaml
  controllers/applicationconnector_controller_test.go
  pkg/reconciler/testdata/update/deps-valid.yaml
  pkg/reconciler/update_objects_test.go
Labels: size/XS, lgtm

#75 Remove crds from yaml files
  .gitignore
  application-connector.yaml
  manifests/application-connector/rendered.yaml
Labels: size/XL, lgtm

#76 Update documentation links
  .env
  config/ui-extensions/applicationconnectors/general
Labels: size/XS, lgtm

#77 Update module security scanner config file
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#69 Improve the AC module documentation
  README.md
  docs/user/02-20-enable-kyma-with-runtime-agent.md
  docs/user/technical-reference/05-10-application-connector-chart.md
Labels: size/S, area/documentation, area/application-connector, lgtm

#74 Update installation guide
  docs/assets/prow_job_status.png
  docs/assets/pull_application-connector_module_build.png
  docs/contributor/01-10-installation.md
Labels: size/L, lgtm

#79 fix table
  docs/contributor/04-10-ci-cd.md
Labels: size/XS, lgtm

#80 Update govulncheck action
  .github/workflows/run-vuln-check.yaml
  go.mod
  go.sum
Labels: size/S, area/ci, lgtm

#81 Release 1.0.0
  .env
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#82 Fix k3d-upgrade-test
  hack/ci/Makefile
Labels: size/XS, lgtm

#85 add the Scripts don't work troubleshooting guide
  docs/contributor/03-10-scripts-dont-work.md
Labels: area/documentation, area/application-connector, lgtm

#88 CR description of Application Connector
  README.md
  docs/user/resources/06-30-application-connector.md
Labels: documentation, size/M, area/documentation, area/application-connector, lgtm

#92 Update image for security scanners
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#93 Provide missing descriptions in the CompassConnection CRD
  docs/user/resources/06-20-compassconnection.md
Labels: size/XS, area/documentation, area/application-connector, lgtm

#96 Fix LeaderElectionID
  main.go
Labels: size/XS, lgtm

#97 New image for release 1.0.0
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#98 Bump version to 1.0.1
  .env
Labels: size/XS, lgtm
