Repository kyma-project/application-connector-manager, pull requests merged in 2023-08, with the labels that each got.

#28 Configure project for CI Testing
  .github/workflows/run-tests.yaml
  .gitignore
  .trivy.yaml
  CODEOWNERS
  Makefile
  README.md
  config/crd/bases/operator.kyma-project.io_applicationconnectors.yaml
  controllers/applicationconnector_controller.go
  controllers/applicationconnector_controller_test.go
  hack/ci/Makefile
  hack/common/Makefile
  manifests/application-connector/rendered.yaml
  pkg/reconciler/apply.go
  pkg/reconciler/cfg.go
  pkg/reconciler/verify.go
Labels: size/M, area/ci, lgtm

#16 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm

#33 Adding Upstream-contact information
  .reuse/dep5
Labels: size/XS, lgtm

#37 add GHA unit tests
  .github/workflows/run-tests.yaml
Labels: size/XS, area/ci, lgtm
