Repository kyma-project/application-connector-manager, pull requests merged in 2023-09, with the labels that each got.

#39 Add PriorityClass to Application Connetor deployments
  application-connector.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/application_controller_rbac.go
Labels: size/M, area/application-connector, lgtm

#43 Remove monitoring virtual service from Runtime Agent
  application-connector.yaml
Labels: size/S, lgtm

#22 Copy AC documentation to the AC module repository
  README.md
  docs/assets/ac-application-connector-architecture.svg
  docs/assets/ac-architecture-proxy-service.svg
  docs/assets/ra-runtime-agent-workflow.svg
  docs/contributor/01-10-installation.md
  docs/user/00-10-application-gateway.md
  docs/user/00-20-security.md
  docs/user/00-30-runtime-agent-overview.md
  docs/user/02-10-pass-access-token-in-request-header.md
  docs/user/02-20-enable-kyma-with-runtime-agent.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/resources/06-10-application.md
  docs/user/resources/06-20-compassconnection.md
  docs/user/resources/README.md
  docs/user/resources/_sidebar.md
  docs/user/technical-reference/04-10-application-connector-components.md
  docs/user/technical-reference/04-20-application-gateway.md
  docs/user/technical-reference/04-30-runtime-agent-workflow.md
  docs/user/technical-reference/05-10-application-connector-chart.md
  docs/user/technical-reference/05-20-connection-with-compass.md
  docs/user/technical-reference/07-10-application-gateway-details.md
  docs/user/technical-reference/07-20-configuring-runtime.md
  docs/user/technical-reference/README.md
  docs/user/technical-reference/_sidebar.md
  docs/user/tutorials/01-10-create-application.md
  docs/user/tutorials/01-100-reconnect-runtime-agent-with-compass.md
  docs/user/tutorials/01-20-register-manage-services.md
  docs/user/tutorials/01-30-register-secured-api.md
  docs/user/tutorials/01-40-call-registered-service-from-kyma.md
  docs/user/tutorials/01-50-disable-tls-certificate-verification.md
  docs/user/tutorials/01-60-establish-secure-connection-with-compass.md
  docs/user/tutorials/01-70-maintain-secure-connection-with-compass.md
  docs/user/tutorials/01-80-revoke-client-certificate.md
  docs/user/tutorials/01-90-configure-runtime-agent-with-compass.md
  docs/user/tutorials/README.md
  docs/user/tutorials/_sidebar.md
Labels: size/XXL, area/documentation, lgtm

#45 Create app connector CRD
  api/v1alpha1/applicationconnector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  application-connector.yaml
  config/crd/bases/operator.kyma-project.io_applicationconnectors.yaml
  config/samples/operator_v1alpha1_applicationconnector.yaml
Labels: size/L, lgtm

#46 copy a paragraph from kyma repo
  docs/user/technical-reference/07-10-application-gateway-details.md
Labels: size/XS, lgtm

#44 Add CRD upgrade handling mechanism and dependency management
  .dockerignore
  .github/workflows/run-tests.yaml
  Dockerfile
  api/v1alpha1/applicationconnector_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  application-connector-dependencies.yaml
  application-connector.yaml
  config/crd/bases/operator.kyma-project.io_applicationconnectors.yaml
  config/samples/operator_v1alpha1_applicationconnector.yaml
  controllers/applicationconnector_controller.go
  controllers/applicationconnector_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/common/types/types.go
  pkg/reconciler/apply.go
  pkg/reconciler/cfg.go
  pkg/reconciler/check_dependencies.go
  pkg/reconciler/common.go
  pkg/reconciler/delete_resources.go
  pkg/reconciler/fn_state_matcher_test.go
  pkg/reconciler/fsm.go
  pkg/reconciler/suite_test.go
  pkg/reconciler/take_snapshot.go
  pkg/reconciler/testdata/update/acm-valid.yaml
  pkg/reconciler/testing/testing.go
  pkg/reconciler/update_objects.go
  pkg/reconciler/update_objects_test.go
  pkg/reconciler/verify.go
  pkg/unstructured/unstructured.go
  pkg/yaml/utils.go
  pkg/yaml/utils_test.go
Labels: size/XXL, area/ci, lgtm

#50 Extend verification of module installation
  pkg/dependencies/istio/gateway.go
  pkg/dependencies/istio/virtual_service.go
  pkg/reconciler/verify.go
  pkg/unstructured/predicate.go
Labels: size/M, lgtm
