Repository kyma-project/application-connector-manager, pull requests merged in 2023-11, with the labels that each got.

#99 Update memory and request limits
  config/manager/manager.yaml
Labels: size/XS, lgtm

#100 Include latest images for application-connector components
  .env
  application-connector.yaml
Labels: size/XS, lgtm

#101 Fix gateway predicate
  pkg/common/controller-runtime/predicate/gateway.go
Labels: size/XS, lgtm

#102 Add AC CR to sidebar
  docs/user/resources/_sidebar.md
Labels: size/XS, lgtm

#107 Enable Markdown Link Check in the ACM repo
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/pr-markdown-link-check.yaml
  .github/workflows/run-vuln-check.yaml
  .mlc.config.json
  Dockerfile
Labels: size/M, area/ci, lgtm

#109 Fix links found by Link Checker
  docs/contributor/04-10-ci-cd.md
  docs/user/technical-reference/_sidebar.md
Labels: size/XS, lgtm

#110 Fix Eventing links in the AC documentation
  docs/user/README.md
Labels: size/XS, lgtm

#111 Change eventing publisher service endpoint to eventing-publisher-proxy.kyma-system
  .env
  CODEOWNERS
  application-connector.yaml
Labels: size/S, lgtm

#112 Update security scanner image to latest version from registry
  sec-scanners-config.yaml
Labels: size/XS, lgtm
