Repository kyma-project/application-connector-manager, pull requests merged in 2023-12, with the labels that each got.

#116 Remove unnecessary sidebars from the ACM repo documentation
  docs/user/_sidebar.md
  docs/user/resources/_sidebar.md
  docs/user/technical-reference/_sidebar.md
  docs/user/tutorials/_sidebar.md
Labels: size/M, lgtm, cla: yes

#117 Remove an obsolete tip
  docs/user/02-20-enable-kyma-with-runtime-agent.md
Labels: size/XS, lgtm, cla: yes

#119 Adjust ACM to new content guidelines
  README.md
  docs/contributor/01-10-installation.md
  docs/contributor/03-10-scripts-dont-work.md
  docs/contributor/04-10-ci-cd.md
  docs/user/00-10-application-gateway.md
  docs/user/00-20-security.md
  docs/user/02-10-pass-access-token-in-request-header.md
  docs/user/_sidebar.md
  docs/user/resources/06-10-application.md
  docs/user/resources/06-20-compassconnection.md
  docs/user/resources/06-30-application-connector.md
  docs/user/resources/README.md
  docs/user/technical-reference/04-10-application-connector-components.md
  docs/user/technical-reference/04-30-runtime-agent-workflow.md
  docs/user/technical-reference/05-20-connection-with-compass.md
  docs/user/technical-reference/07-10-application-gateway-details.md
  docs/user/technical-reference/README.md
  docs/user/tutorials/01-10-create-application.md
  docs/user/tutorials/01-20-register-manage-services.md
  docs/user/tutorials/01-30-register-secured-api.md
  docs/user/tutorials/01-40-call-registered-service-from-kyma.md
  docs/user/tutorials/01-50-disable-tls-certificate-verification.md
  docs/user/tutorials/01-60-establish-secure-connection-with-compass.md
  docs/user/tutorials/01-70-maintain-secure-connection-with-compass.md
  docs/user/tutorials/01-80-revoke-client-certificate.md
  docs/user/tutorials/01-90-configure-runtime-agent-with-compass.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#120 Create dependabot.yml for application-connector-manager
  .github/dependabot.yml
Labels: size/S, area/ci, lgtm, cla: yes

#115 Change behaviour of state machine to requeue reconcilation after error
  .github/workflows/run-vuln-check.yaml
  Dockerfile
  application-connector.yaml
  pkg/reconciler/apply.go
  pkg/reconciler/check_dependencies.go
  pkg/reconciler/common.go
  pkg/reconciler/delete_resources.go
  pkg/reconciler/detect_domain.go
  pkg/reconciler/initialize.go
  pkg/reconciler/manage_compass_rt_agent.go
  pkg/reconciler/update_objects.go
  pkg/reconciler/verify.go
Labels: size/M, area/ci, lgtm, cla: yes

#127 k8s.io components bump to 0.29.0
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#131 Application Connector - prepare module release version 1.0.5
  .env
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#133 Adding all components in the module to security scanner configuration file
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes
