Repository kyma-project/application-connector-manager, pull requests merged in 2024-03, with the labels that each got.

#184 Remove build-module action
  .github/workflows/build-module.yaml
Labels: size/M, area/ci, lgtm, cla: yes

#187 Add trivy workflow
  .github/workflows/trivy.yml
Labels: size/M, area/ci, lgtm, cla: yes

#186 Clean module build unused code
  Makefile
  docs/contributor/01-10-installation.md
  docs/contributor/04-10-ci-cd.md
  hack/ci/Makefile
  hack/common/Makefile
  hack/local/Makefile
Labels: size/L, lgtm, cla: yes

#193 Update TOC in the AC installation doc
  docs/contributor/01-10-installation.md
Labels: size/XS, lgtm, cla: yes

#185 [ACM] Rename the GitHub Actions
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/pr-markdown-link-check.yaml
  .github/workflows/run-tests.yaml
  .github/workflows/run-validation.yaml
  .github/workflows/run-vuln-check.yaml
  Dockerfile
Labels: size/S, area/ci, lgtm, cla: yes

#202 Move CRA to app con manager
  application-connector.yaml
  controllers/applicationconnector_controller.go
  controllers/applicationconnector_controller_test.go
  controllers/predicate.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/common/Makefile
  hack/common/k3d-patches/patch-cra-crds.yaml
  pkg/reconciler/cra_matcher_test.go
  pkg/reconciler/fn_state_matcher_test.go
  pkg/reconciler/initialize.go
  pkg/reconciler/manage_compass_rt_agent.go
  pkg/reconciler/update_objects.go
Labels: size/XXL, lgtm, cla: yes

#208 Move ACM CRDs from kyma repository
  application-connector.yaml
  controllers/applicationconnector_controller.go
  controllers/predicate.go
  hack/common/Makefile
  hack/common/k3d-patches/patch-cra-crds.yaml
Labels: size/XL, lgtm, cla: yes

#210 Prepare ACM for the new release with Compass Runtime Agent
  .env
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#211 Release with CRA
  application-connector.yaml
Labels: size/XS, lgtm, cla: yes

#217 Fix link in the compassconnection readme
  docs/user/resources/06-20-compassconnection.md
Labels: size/XS, lgtm, cla: yes

#209 Apply markdowlint rules in the ACM repository
  .markdownlint.yaml
  .markdownlintignore
  docs/contributor/01-10-installation.md
  docs/contributor/03-10-scripts-dont-work.md
  docs/contributor/04-10-ci-cd.md
  docs/user/00-10-application-gateway.md
  docs/user/00-20-security.md
  docs/user/00-30-runtime-agent-overview.md
  docs/user/02-10-pass-access-token-in-request-header.md
  docs/user/02-20-enable-kyma-with-runtime-agent.md
  docs/user/resources/06-10-application.md
  docs/user/resources/06-20-compassconnection.md
  docs/user/resources/06-30-application-connector.md
  docs/user/technical-reference/04-10-application-connector-components.md
  docs/user/technical-reference/04-20-application-gateway.md
  docs/user/technical-reference/04-30-runtime-agent-workflow.md
  docs/user/technical-reference/05-20-connection-with-compass.md
  docs/user/technical-reference/07-10-application-gateway-details.md
  docs/user/technical-reference/07-20-configuring-runtime.md
  docs/user/technical-reference/README.md
  docs/user/tutorials/01-10-create-application.md
  docs/user/tutorials/01-100-reconnect-runtime-agent-with-compass.md
  docs/user/tutorials/01-20-register-manage-services.md
  docs/user/tutorials/01-30-register-secured-api.md
  docs/user/tutorials/01-40-call-registered-service-from-kyma.md
  docs/user/tutorials/01-50-disable-tls-certificate-verification.md
  docs/user/tutorials/01-60-establish-secure-connection-with-compass.md
  docs/user/tutorials/01-70-maintain-secure-connection-with-compass.md
  docs/user/tutorials/01-80-revoke-client-certificate.md
  docs/user/tutorials/01-90-configure-runtime-agent-with-compass.md
  docs/user/tutorials/README.md
  markdown_heading_capitalization.js
Labels: size/XL, lgtm, cla: yes
