Repository kyma-project/application-connector-manager, pull requests merged in 2024-07, with the labels that each got.

#293 New Image Builder
  .github/workflows/build.yaml
  Dockerfile
  go.mod
Labels: size/M, area/ci, lgtm, cla: yes

#294 Change paths for image builder
  Dockerfile
Labels: size/XS, lgtm, cla: yes

#300 Prepare 1.1.6 release
  .env
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#301 Fix links
  docs/contributor/04-10-ci-cd.md
  docs/user/tutorials/01-60-establish-secure-connection-with-compass.md
  docs/user/tutorials/01-70-maintain-secure-connection-with-compass.md
  docs/user/tutorials/01-80-revoke-client-certificate.md
Labels: size/XS, lgtm, cla: yes

#303 add initial version of test-protocol template
  .github/ISSUE_TEMPLATE/test-protocol.md
Labels: size/M, area/ci, lgtm, cla: yes

#305 ACM Tag Builds + workflow restructure
  .github/workflows/acm.yaml
  .github/workflows/build.yaml
  .github/workflows/run-tests.yaml
Labels: size/L, area/ci, lgtm, cla: yes

#306 Remove dorny/paths-filter action
  .github/workflows/acm.yaml
Labels: size/M, area/ci, lgtm, cla: yes

#307 Add summary, fix outputs access
  .github/workflows/acm.yaml
Labels: size/S, area/ci, lgtm, cla: yes

#308 Add missing `runs-on`
  .github/workflows/acm.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#310 Fix link in CICD
  docs/contributor/04-10-ci-cd.md
Labels: size/XS, lgtm, cla: yes

#311 Change enable and disable to add and delete in the ACM repo
  docs/user/README.md
Labels: size/XS, lgtm, cla: yes
