Repository kyma-project/application-connector-manager, pull requests merged in 2024-08, with the labels that each got.

#297 Build rest of the images with GHA
  .github/workflows/central-application-gateway-unit-test.yaml
  .github/workflows/compass-runtime-agent-unit-test.yaml
  .github/workflows/connectivity-validator-unit-test.yaml
  .github/workflows/cra.yaml
  .github/workflows/gateway.yaml
  .github/workflows/kyma-integration-k3d-agent-tests.yml
  .github/workflows/kyma-integration-k3d-app-gateway.yml
  .github/workflows/kyma-integration-k3d-validator-tests.yml
  .github/workflows/validator.yaml
Labels: size/L, area/ci, lgtm, cla: yes

#316 Fix path selectors, Add missing build jobs
  .github/workflows/cra.yaml
  .github/workflows/gateway.yaml
  .github/workflows/validator.yaml
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-gateway/Dockerfile
  components/compass-runtime-agent/Dockerfile
  tests/Dockerfile.compass-runtime-agent
  tests/Dockerfile.connectivity-validator
  tests/Dockerfile.gateway
  tests/Dockerfile.mockapp
Labels: size/M, area/ci, lgtm, cla: yes

#309 Improve ACM pipeline reporting
  .github/workflows/acm.yaml
Labels: size/S, area/ci, lgtm, cla: yes

#313 Convert test-protocol template to form
  .github/ISSUE_TEMPLATE/test-protocol.md
  .github/ISSUE_TEMPLATE/test-protocol.yaml
Labels: size/L, area/ci, lgtm, cla: yes

#318 Fix links in the ci/cd doc
  docs/contributor/04-10-ci-cd.md
Labels: size/XS, lgtm, cla: yes

#315 Add caching
  components/central-application-gateway/internal/metadata/applications/repository.go
  components/central-application-gateway/internal/metadata/applications/repository_test.go
  components/central-application-gateway/internal/metadata/secrets/repository.go
  components/central-application-gateway/internal/metadata/secrets/repository_test.go
Labels: size/L, lgtm, cla: yes
