Repository kyma-project/application-connector-manager, pull requests merged in 2024-09, with the labels that each got.

#327 Fix pipelines, improve summaries
  .github/workflows/acm.yaml
  .github/workflows/cra.yaml
  .github/workflows/reusable-k3d-agent-test.yml
Labels: size/M, area/ci, lgtm, cla: yes

#328 docs: Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, lgtm, cla: yes

#330 docs: Add code of conduct and update readme
  CODE_OF_CONDUCT.md
  README.md
Labels: size/S, lgtm, cla: yes

#331 Fix pipelines summary and checkout repo
  .github/workflows/acm.yaml
  .github/workflows/cra.yaml
  .github/workflows/reusable-k3d-agent-test.yml
Labels: size/L, area/ci, lgtm, cla: yes

#332 Checkout with PR event vars
  .github/workflows/cra.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#335 Fix test summary formatting, fix e2e checkout
  .github/workflows/cra.yaml
  .github/workflows/reusable-k3d-agent-test.yml
Labels: size/S, area/ci, lgtm, cla: yes

#336 Fix `tee` params for summaries
  .github/workflows/cra.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#337 Improve CRA summary
  .github/workflows/cra.yaml
Labels: size/S, area/ci, lgtm, cla: yes

#338 Add missing `>>`
  .github/workflows/cra.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#340 Fix pipelines checkouts + summaries
  .github/workflows/acm.yaml
  .github/workflows/cra.yaml
  .github/workflows/gateway.yaml
  .github/workflows/reusable-k3d-agent-test.yml
  .github/workflows/validator.yaml
Labels: size/L, area/ci, lgtm, cla: yes

#342 Fix summaries and skips
  .github/workflows/acm.yaml
  .github/workflows/cra.yaml
  .github/workflows/gateway.yaml
  .github/workflows/reusable-k3d-agent-test.yml
  .github/workflows/validator.yaml
Labels: size/M, area/ci, lgtm, cla: yes

#339 Update dependencies for application-connector components to latest versions
  Dockerfile
  components/central-application-connectivity-validator/.gitignore
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/.gitignore
  components/central-application-gateway/Dockerfile
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/.gitignore
  components/compass-runtime-agent/Dockerfile
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  go.mod
  go.sum
  tests/.gitignore
  tests/Dockerfile.compass-runtime-agent
  tests/Dockerfile.connectivity-validator
  tests/Dockerfile.gateway
  tests/Dockerfile.mockapp
  tests/go.mod
  tests/go.sum
Labels: size/XXL, lgtm, cla: yes

#345 Update golang version to 1.23.0
  .github/workflows/gateway.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/reusable-k3d-agent-test.yml
  .github/workflows/run-validation.yaml
  .github/workflows/run-vuln-check.yaml
  .github/workflows/validator.yaml
  Dockerfile
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-connectivity-validator/go.mod
  components/central-application-gateway/Dockerfile
  components/central-application-gateway/go.mod
  components/compass-runtime-agent/Dockerfile
  components/compass-runtime-agent/go.mod
  go.mod
  tests/Dockerfile.compass-runtime-agent
  tests/Dockerfile.connectivity-validator
  tests/Dockerfile.gateway
  tests/Dockerfile.mockapp
  tests/go.mod
  tests/go.sum
Labels: size/M, area/ci, lgtm, cla: yes

#348 Configuration of the application-connector module for new release 1.1.7
  .env
  application-connector.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, cla: yes

#349 Fix of golangci-lint gh action
  .github/workflows/golangci-lint.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#354 Update Golang version to 1.23.1
  .github/workflows/gateway.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/reusable-k3d-agent-test.yml
  .github/workflows/run-validation.yaml
  .github/workflows/run-vuln-check.yaml
  .github/workflows/validator.yaml
  Dockerfile
  components/central-application-connectivity-validator/Dockerfile
  components/central-application-connectivity-validator/go.mod
  components/central-application-gateway/Dockerfile
  components/central-application-gateway/go.mod
  components/compass-runtime-agent/Dockerfile
  components/compass-runtime-agent/go.mod
  go.mod
  tests/Dockerfile.compass-runtime-agent
  tests/Dockerfile.connectivity-validator
  tests/Dockerfile.gateway
  tests/Dockerfile.mockapp
  tests/go.mod
Labels: size/M, area/ci, lgtm, cla: yes

#355 Prepare release 1.1.8
  .env
  application-connector.yaml
  manifest.yaml
  sec-scanners-config.yaml
Labels: size/XL, lgtm, cla: yes

#356 remove manifest
  manifest.yaml
Labels: size/XL, lgtm, cla: yes

#360 Remove the obsolete Runtime Agent warning
  docs/user/00-30-runtime-agent-overview.md
  docs/user/02-20-enable-kyma-with-runtime-agent.md
  docs/user/README.md
  docs/user/resources/06-10-application.md
  docs/user/resources/06-20-compassconnection.md
  docs/user/technical-reference/04-30-runtime-agent-workflow.md
  docs/user/technical-reference/05-20-connection-with-compass.md
  docs/user/technical-reference/07-20-configuring-runtime.md
  docs/user/tutorials/01-100-reconnect-runtime-agent-with-compass.md
  docs/user/tutorials/01-60-establish-secure-connection-with-compass.md
  docs/user/tutorials/01-70-maintain-secure-connection-with-compass.md
  docs/user/tutorials/01-80-revoke-client-certificate.md
  docs/user/tutorials/01-90-configure-runtime-agent-with-compass.md
Labels: size/M, lgtm, cla: yes

#357 Compass Runtime Agent - Normalise Compass application names during synchronisation
  .gitignore
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  components/compass-runtime-agent/internal/compassconnection/package_test.go
  components/compass-runtime-agent/internal/compassconnection/supervisor.go
  components/compass-runtime-agent/internal/kyma/applications/normalizer.go
  components/compass-runtime-agent/internal/kyma/applications/normalizer_test.go
  components/compass-runtime-agent/internal/kyma/mocks/Service.go
  components/compass-runtime-agent/internal/kyma/service.go
  components/compass-runtime-agent/internal/kyma/service_test.go
  docs/user/technical-reference/07-20-configuring-runtime.md
Labels: size/XL, lgtm, cla: yes
