Repository kyma-project/application-connector-manager, pull requests merged in 2024-05, with the labels that each got.

#263 Bump go to 1.22.3
  .github/workflows/golangci-lint.yaml
  .github/workflows/kyma-integration-k3d-app-gateway.yml
  .github/workflows/kyma-integration-k3d-validator-tests.yml
  .github/workflows/reusable-k3d-agent-test.yml
  .github/workflows/run-tests.yaml
  .github/workflows/run-validation.yaml
  .github/workflows/run-vuln-check.yaml
  Dockerfile
  go.mod
  tests/Dockerfile.compass-runtime-agent
  tests/Dockerfile.connectivity-validator
  tests/Dockerfile.gateway
  tests/Dockerfile.mockapp
  tests/go.mod
Labels: size/M, area/ci, lgtm, cla: yes

#260 Deprecate kyma provision k3d command
  tests/docs/application-connectivity-validator-tests.md
  tests/docs/application-gateway-tests.md
  tests/docs/compass-runtime-agent-tests.md
  tests/scripts/test-cra.sh
Labels: size/S, lgtm, cla: yes

#266 fix: Change timestamp format for logs
  main.go
Labels: kind/bug, size/XS, lgtm, cla: yes

#269 Unify the CR description in Kyma dashoard
  config/ui-extensions/applicationconnectors/general
Labels: documentation, size/XS, lgtm, cla: yes

#275 Move unit tests from prow
  .github/workflows/central-application-gateway-unit-test.yaml
  .github/workflows/compass-runtime-agent-unit-test.yaml
  .github/workflows/connectivity-validator-unit-test.yaml
  components/central-application-connectivity-validator/Makefile
  components/compass-runtime-agent/Makefile
Labels: size/M, area/ci, lgtm, cla: yes
