Repository kyma-project/application-connector-manager, pull requests merged in 2024-10, with the labels that each got.

#364 feat: Add proper categories for CRDs
  Makefile
  api/v1alpha1/applicationconnector_types.go
  config/crd/bases/operator.kyma-project.io_applicationconnectors.yaml
  config/rbac/role.yaml
Labels: size/M, lgtm, cla: yes

#365 switches daily-markdown-link-check action to a concrete sha version
  .github/workflows/daily-markdown-link-check.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#370 switches pr-markdown-link-check version to whitelisted one
  .github/workflows/pr-markdown-link-check.yaml
Labels: size/XS, area/ci, lgtm, cla: yes

#371 Update links to Istio docs
  docs/user/tutorials/01-10-create-application.md
  docs/user/tutorials/01-20-register-manage-services.md
  docs/user/tutorials/01-40-call-registered-service-from-kyma.md
Labels: size/XS, lgtm, cla: yes
