Repository kyma-project/application-connector-manager, pull requests merged in 2024-04, with the labels that each got.

#225 add workaround to avoid upgrade fail
  application-connector.yaml
Labels: size/XS, lgtm, cla: yes

#224 fix security vulnerabilities
  .github/workflows/golangci-lint.yaml
  .github/workflows/kyma-integration-k3d-app-gateway.yml
  .github/workflows/kyma-integration-k3d-validator-tests.yml
  .github/workflows/run-tests.yaml
  .github/workflows/run-validation.yaml
  .github/workflows/run-vuln-check.yaml
  go.mod
  go.sum
  tests/go.mod
  tests/go.sum
Labels: size/M, area/ci, lgtm, cla: yes

#215 Remove CRA migration permissions
  application-connector.yaml
Labels: size/S, lgtm, cla: yes

#230 Prepare for release 1.1.1
  .env
  application-connector.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, cla: yes

#236 bumps k3d version to 5.6.0
  .github/workflows/kyma-integration-k3d-agent-tests.yml
  .github/workflows/kyma-integration-k3d-app-gateway.yml
  .github/workflows/kyma-integration-k3d-validator-tests.yml
  .github/workflows/reusable-k3d-agent-test.yml
  hack/ci/Makefile
Labels: size/S, area/ci, lgtm, cla: yes

#235 Remove mentions of chaos and load tests
  docs/contributor/04-10-ci-cd.md
Labels: size/XS, lgtm, cla: yes

#245 remove caching from workflows
  .github/workflows/kyma-integration-k3d-agent-tests.yml
  .github/workflows/kyma-integration-k3d-app-gateway.yml
  .github/workflows/kyma-integration-k3d-validator-tests.yml
  .github/workflows/reusable-k3d-agent-test.yml
  .github/workflows/run-tests.yaml
  .github/workflows/run-validation.yaml
  tests/Makefile
  tests/Makefile.test-compass-runtime-agent
Labels: size/M, area/ci, lgtm, cla: yes

#249 Remove presubmit-scanner job from cicd doc
  docs/contributor/04-10-ci-cd.md
Labels: size/XS, lgtm, cla: yes

#243 Fix event and console URL for compass-runtime-agent
  api/v1alpha1/applicationconnector_types.go
  go.mod
  pkg/reconciler/cra_matcher_test.go
  pkg/reconciler/initialize.go
  pkg/reconciler/manage_compass_rt_agent.go
  pkg/reconciler/testdata/update/acm-valid.yaml
  pkg/reconciler/update_objects.go
  pkg/reconciler/update_objects_test.go
Labels: size/L, lgtm, cla: yes

#250 Prepare release 1.1.3
  application-connector.yaml
  sec-scanners-config.yaml
Labels: size/S, lgtm, cla: yes

#257 Remove kyma-system namespace from project
  config/manager/manager.yaml
Labels: size/S, lgtm, cla: yes

#258 Release version 1.1.4
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes
