Repository kyma-project/application-connector-manager, pull requests merged in 2024-12, with the labels that each got.

#395 Fix sidebar
  docs/user/_sidebar.md
  docs/user/technical-reference/README.md
Labels: size/S, lgtm, cla: yes

#396 Fix broken links
  components/central-application-gateway/README.md
  docs/user/tutorials/01-50-disable-tls-certificate-verification.md
Labels: documentation, size/XS, area/documentation, lgtm, cla: yes

#400 replaces golang.org/x/crypto to v0.31.0
  go.mod
  go.sum
Labels: size/S, lgtm, cla: yes

#401 replace golang.org/x/crypto to v0.31.0 also for components and tests
  components/central-application-connectivity-validator/go.mod
  components/central-application-connectivity-validator/go.sum
  components/central-application-gateway/go.mod
  components/central-application-gateway/go.sum
  components/compass-runtime-agent/go.mod
  components/compass-runtime-agent/go.sum
  tests/go.mod
  tests/go.sum
Labels: size/M, lgtm, cla: yes
