Repository kyma-project/application-connector-manager, pull requests merged in 2024-02, with the labels that each got.

#161 [Fix vulnerability] Bump Validator image in chart
  application-connector.yaml
Labels: size/XS, lgtm, cla: yes

#162 Prepare ACM for the new patch release
  .env
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#164 adds security policy
  SECURITY.md
Labels: size/XS, lgtm, cla: yes

#165 Add a licence file
  LICENSE
Labels: size/L, lgtm, cla: yes

#168 Change on cluster to in cluster
  README.md
  docs/contributor/01-10-installation.md
  docs/contributor/04-10-ci-cd.md
  docs/user/resources/06-30-application-connector.md
Labels: size/S, lgtm, cla: yes

#183 bumps golangci-lint to v4.0.0 setup-go to v5, checkout to v4,
  .github/workflows/golangci-lint.yaml
Labels: size/S, area/ci, lgtm, cla: yes

#179 publishing ACM artifacts
  .github/workflows/build-module.yaml
Labels: size/S, area/ci, lgtm, cla: yes
